apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi          
  accessModes:
    - ReadWriteOnce      
  hostPath:
    path: /data/my-app   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-volume
  template:
    metadata:
      labels:
        app: my-app-volume
    spec:
      containers:
      - name: my-app
        image: seojunny/my-app:latest
        volumeMounts:
        - name: my-storage
          mountPath: /app/data    
      volumes:
      - name: my-storage
        persistentVolumeClaim:
          claimName: my-pvc       