apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: seojunny/my-app:409a8aaae184928c7534e6a011a875c8312b9e21
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: APP_NAME 
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_NAME
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30000
  type: NodePort